config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :index ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :value, :inclusion => { :in => 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    set_restaurant
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurants_path
  end

  def edit
    set_restaurant
  end

  def update
    set_restaurant
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    set_restaurant
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :rating, :content)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    set_restaurant
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    set_restaurant
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurants_path
  end

  def edit
    set_review
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant infos</h1>
<div class="form">
  <%= render "form", restaurant: @restaurant %>
</div>
<div class="redirect">
  <p><%= link_to "back", restaurants_path %></p>
</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<div class="container">
  <ul id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <li>
        <div class="restaurant-infos">
          <%= restaurant.name%> - <%= restaurant.category%> - <%= restaurant.address %> - <%= restaurant.phone_number %>
        </div>
        <div class="action-links">
          <p><%= link_to "Reviews", restaurant_path(restaurant.id) %>- <%= link_to "Edit", edit_restaurant_path(restaurant.id) %> - <%= button_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Delete?" } %></p>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="create">
    <p><%= link_to "Add a new restaurant", new_restaurant_path %></p>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Add your restaurant</h1>
<div class="form">
  <%= render "form", restaurant: @restaurant %>
</div>
<div class="redirect">
  <p><%= link_to "back", restaurants_path %></p>
</div>

app/views/restaurants/show.html.erb
<h1>Review</h1>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %> - <%= review.rating %></li>
  <% end %>
</ul>
<div class="create">
  <%= link_to "Add review", new_restaurant_review_path([:restaurant_id]) %>
</div>


<div class="redirect">
  <p><%= link_to "back", restaurants_path %></p>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add your review</h1>
<div class="form">
  <%= render "form", review: @review %>
</div>
<div class="redirect">
  <p><%= link_to "back", restaurants_path %></p>
</div>